apiVersion: v1
kind: Pod
metadata:
  labels:
    run: jr
  name: jr
spec:
  containers:
  - image: nginx
    name: nginx
  - image: busybox
    name: busybox
    args:
    - sleep
    - "600"  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
